export const rows = [
  {
    id: 1,
    username: "Snow Jon",
    email: "nickhassan@gmail.com",
    age: 35,
    phone: "959797347550",
    address: "Mandalay, Chanmyatharzi",
  },
  {
    id: 2,
    username: "Lannister Cersei",
    email: "nickhassan@gmail.com",
    age: 42,
    phone: "959797347550",
    address: "Mandalay, Chanmyatharzi",
  },
  {
    id: 3,
    username: "Lannister Jaime",
    email: "nickhassan@gmail.com",
    age: 45,
    phone: "959797347550",
    address: "Mandalay, Chanmyatharzi",
  },
  {
    id: 4,
    username: "Stark Arya",
    email: "nickhassan@gmail.com",
    age: 16,
    phone: "959797347550",
    address: "Mandalay, Chanmyatharzi",
  },
  {
    id: 5,
    username: "Targaryen Daenerys",
    email: "nickhassan@gmail.com",
    age: 20,
    phone: "959797347550",
    address: "Mandalay, Chanmyatharzi",
  },
  {
    id: 6,
    username: "Melisandre",
    email: "nickhassan@gmail.com",
    age: 15,
    phone: "959797347550",
    address: "Mandalay, Chanmyatharzi",
  },
  {
    id: 7,
    username: "Clifford Ferrara",
    email: "nickhassan@gmail.com",
    age: 44,
    phone: "959797347550",
    address: "Mandalay, Chanmyatharzi",
  },
  {
    id: 8,
    username: "Frances Rossini",
    email: "nickhassan@gmail.com",
    age: 36,
    phone: "959797347550",
    address: "Mandalay, Chanmyatharzi",
  },
  {
    id: 9,
    username: "Roxie Harvey",
    email: "nickhassan@gmail.com",
    age: 65,
    phone: "959797347550",
    address: "Mandalay, Chanmyatharzi",
  },
];
